name: csv2json
description: csv2json is a versatile Dart package designed to simplify the conversion of Comma-Separated Values (CSV) data to JavaScript Object Notation (JSON) format.
version: 0.0.3
repository: https://github.com/Colin-Stark/csv2json.git
homepage: https://github.com/Colin-Stark/csv2json.git

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

license: BSD-3-Clause
