name: csv2json
description: A Dart package for converting CSV data to JSON format.
version: 0.0.2
repository: https://github.com/Colin-Stark/csv2json.git
homepage: https://github.com/Colin-Stark/csv2json.git

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

license: BSD-3-Clause
